spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.80.128:3306/mp?useSSL=false
    username: root
    password: 123456
  flyway:
    locations: classpath:flyway
mybatis:
  mapper-locations: classpath:mapper/**.xml
